#!/usr/bin/env node

// ==UserScript==
// @name               Hide youtube google ad
// @namespace          vince.youtube
// @version            3.0.1
// @description        hide youtube google ad, auto click "skip ad"
// @match              *://www.youtube.com/*
// ==/UserScript==
const qutejs = require('qutejs');

qutejs.jseval([], () => {
  hideAd();
  skipAd();

  function skipAd() {
    const skipInt = setInterval(skipAdInterval, 500);
    function skipAdInterval() {
      const skipbtn =
        document.querySelector('.ytp-ad-skip-button.ytp-button') ||
        document.querySelector('.videoAdUiSkipButton ');
      if (!skipbtn) {
        return;
      }
      skipbtn.click();
      clearInterval(skipInt);
    }
  }

  function hideAd() {
    const css = `
    .video-ads .ad-container .adDisplay,
    #player-ads,.ytp-ad-module,
    .ytp-ad-image-overlay { 
      display: none!important; 
    }`;
    const head = document.head || document.getElementsByTagName('head')[0];
    const style = document.createElement('style');
    style.type = 'text/css';

    if (style.styleSheet) {
      style.styleSheet.cssText = css;
    } else {
      style.appendChild(document.createTextNode(css));
    }

    head.appendChild(style);
  }

  function hideAd2() {
    const queries = [
      '.video-ads .ad-container .adDisplay',
      '#player-ads',
      '.ytp-ad-module',
      '.ytp-ad-image-overlay',
    ]
      .map(q => document.querySelector(q))
      .filter(Boolean)
      .map(e => e.parentNode.removeChild(e));
  }
});
