#!/bin/env python

import os
from datetime import datetime
from lxml import etree
from urllib.parse import parse_qs, urlparse


def get_param(url: str, param: str):
    return (parse_qs(urlparse(url).query).get(param) or ["-1"])[0]


filename = "/tmp/mix_qute_shit"
base = "https://www.youtube.com"
html = os.environ["QUTE_HTML"]
id = get_param(os.environ["QUTE_URL"], "v")
parser = etree.XMLParser(recover=True)
root = etree.parse(html, parser=parser).getroot()
links = root.xpath("//ytd-playlist-panel-video-renderer/a[@id='wc-endpoint']")
urls = ""

for i, a in enumerate(links):
    if get_param(a.attrib["href"], "v") != id:
        continue
    for a in links[i:]:
        href = a.attrib["href"]
        urls += base + href + "\n"

with open(filename, "w") as f:
    f.write(urls)

os.system(f"echo spawn mpv --no-resume-playback --playlist={filename} >> $QUTE_FIFO")
