#!/bin/env python

import os
from lxml import etree
from urllib.parse import parse_qs, urlparse


def get_index(url: str):
    return int((parse_qs(urlparse(url).query).get("index") or ["-1"])[0])


filename = "/tmp/mix_qute_shit"
base = "https://www.youtube.com"
html = os.environ["QUTE_HTML"]
index = get_index(os.environ["QUTE_URL"])
parser = etree.XMLParser(recover=True)
root = etree.parse(html, parser=parser).getroot()
urls = ""

for a in root.xpath("//ytd-playlist-panel-video-renderer//a[@id='wc-endpoint']"):
    href = a.attrib["href"]
    if get_index(href) >= index:
        urls += base + href + "\n"

with open(filename, "w") as f:
    f.write(urls)

os.system(f"echo spawn mpv --playlist={filename} >> $QUTE_FIFO")
