#!/bin/bash
dotfiles_dir=$(realpath -P $(dirname $0))

update-links () {
  src_path=${1}
  dst_path=${2}

  if [[ -d ${src_path} ]]; then
    files=($(ls -A ${src_path})) # files to array

    for file in "${files[@]}"
    do
      rm -rf "${dst_path}/${file}" # rm if exists or not exists)
      ln -s "${src_path}/${file}" "${dst_path}/${file}"
    done
  elif [[ -f ${src_path} ]]; then
    file=$(basename ${src_path})
    rm -rf "${dst_path}" # rm if exists or not exists)
    ln -s "${src_path}" "${dst_path}"
  else
    echo "Invalid path: ${src_path}"
    exit 1
  fi
}

update-links ${dotfiles_dir}/Home "${HOME}"
update-links ${dotfiles_dir}/Config "${HOME}/.config"
update-links ${dotfiles_dir}/Config/fish/fish_history "${HOME}/.local/share/fish/fish_history"
