#!/bin/bash

# Set environment
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
export GOLDEN_RATIO=0.6180339887498948

austart sxhkd
austart compton
austart xfce4-power-manager 2> /dev/null
austart copyq
austart polybar
sleep 0.01 ; polybar-msg hide
# ./$XDG_CONFIG_HOME/polybar/launch.sh

xset r rate 250 30

# add background
austart bgInterval

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           16 

bspc config split_ratio                 $GOLDEN_RATIO
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc desktop '^1' --layout monocle
bspc desktop '^2' --layout monocle

bspc rule --add "glue"                      sticky=on
bspc rule --add discord                     desktop='^1' follow=on
bspc rule --add Discord                     desktop='^1' follow=on
bspc rule --add firefox                     desktop='^2' follow=on
bspc rule --add qutebrowser                 desktop='^2' follow=on
bspc rule --add VirtualBox                  desktop='^4' follow=on

# Colors
# shellcheck source=/dev/null
# . "$HOME/.local/share/themes/colorschemes/bspwm.cfg"
# bspc config focused_border_color            "$brightwhite"
# bspc config active_border_color             "$brightblack"
# bspc config normal_border_color             "$black"
# bspc config urgent_border_color             "$blue"
# bspc config presel_feedback_color           "$yellow"
# bspc config focused_locked_border_color     "$brightred"
# bspc config active_locked_border_color      "$red"
# bspc config normal_locked_border_color      "$black"
# bspc config focused_sticky_border_color     "$brightcyan"
# bspc config active_sticky_border_color      "$cyan"
# bspc config normal_sticky_border_color      "$black"
# bspc config focused_private_border_color    "$brightblue"
# bspc config active_private_border_color     "$blue"
# bspc config normal_private_border_color     "$black"

