alias @="sudo"
alias gc="git add -A && git commit -m "
alias ls="ls --color"
alias la="ls -Alh"
alias l="ls -A"
alias h="history 1 | grep"
alias emacs="emacs -nw"
alias rm="rm -rf"
alias pacman="sudo pacman"
alias zathura="zathura --mode fullscreen"
alias nv="nvim"
alias myip='dig @resolver4.opendns.com myip.opendns.com +short' 
alias myip4='dig @resolver4.opendns.com myip.opendns.com +short -4'
alias myip6='dig @ns1.google.com TXT o-o.myaddr.l.google.com +short -6'
alias ~="cd $HOME"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

