alias ~="cd $HOME"
alias ..="cd .."
alias /="cd /"
alias gc="git add -A && git commit -m "
alias ls="ls --color"
alias la="ls -Alh"
alias l="ls -A"
alias h="history 1 | grep"
alias emacs="emacs -nw"

