[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
# target-cpu = "native"

[net]
git-fetch-with-cli = true

# [unstable]
# codegen-backend = true
#
# [profile.dev]
# codegen-backend = "cranelift"

# 

[registries.kellnr]
index = "sparse+https://crates.swind.sk/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "<redacted>"
