[language.cpp]
command = "ccls"
synchronous_timeout_ms = 300
num_server_instances = 2
always_prefer = false

[language.c]
command = "ccls"
synchronous_timeout_ms = 300
num_server_instances = 2
always_prefer = false

[language.rust]
command = "rls"
synchronous_timeout_ms = 300
num_server_instances = 2

[language.javascript]
command = "typescript-language-server"
args = ["--stdio"]
#install = [["npm", "install", "-g", "typescript-language-server"]]

[language.typescript]
command = "typescript-language-server"
args = ["--stdio"]
#install = [["npm", "install", "-g", "typescript-language-server"]]

[language.html]
command = "html-languageserver"
args = ["--stdio"]
#install = [["npm", "install", "-g", "vscode-html-languageserver-bin"]]

[language.css]
command = "css-languageserver"
args = ["--stdio"]
#install = [["npm", "install", "-g", "vscode-css-languageserver-bin"]]

[language.python]
command = "pyls"
# install = [["pip", "install", "python-language-server"]]

[language.haskell]
command = "haskell-language-server-wrapper"
args = ["--lsp"]

#[language.go]
#command = "gopls"
#args = ["serve"]
#install = [["go", "get", "-u", "golang.org/x/tools/gopls"]]

[language.viml]
command = "vim-language-server"
args = ["--stdio"]
#install = [["npm", "install", "-g", "vim-language-server"]]

