[FileDialog]
history=file:///home/ddystopia/job/metrix, file:///tmp, file:///home/ddystopia, file:///home/ddystopia/job/chart_title_bug, file:///home/ddystopia/Documents/S-colne, file:///home/ddystopia/.local/cache/nvim/undodir
lastVisited=file:///home/ddystopia/.local/cache/nvim/undodir
qtVersion=6.11.0
shortcuts=file:, file:///home/ddystopia
sidebarWidth=97
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3.\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x1\v\0\0\0\x1\0\0\0\0\0\0\0_\0\0\0\x1\0\0\0\0\0\0\0@\0\0\0\x1\0\0\0\0\0\0\x1\x84\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
